export const COFFEE_OPTIONS = {
  roastLevels: [
    'Light',
    'Light-Medium',
    'Medium',
    'Medium-Dark',
    'Dark',
    'Extra-Dark',
  ] as const,

  tastingNotes: [
    'Berry Fruit',
    'Brown Sugar',
    'Citrus',
    'Earthiness',
    'Florals',
    'Milk Chocolate',
    'Nut',
    'Ripe Fruit',
    'Roastiness',
    'Savoriness',
    'Spice',
    'Sweet Vanilla',
    'Tropical Fruit',
  ] as const,

  // priceRanges: [
  //   'Any',
  //   '$15.75',
  //   '$19.95',
  //   '$20 - $25',
  //   'Over $25',
  // ] as const,

  regions: [
    'Africa',
    'Asia',
    'Central America',
    'North America',
    'South America',
  ] as const,

  origins: [
    'Bolivia',
    'Brazil',
    'Burundi',
    'Colombia',
    'Congo',
    'Costa Rica',
    'East Timor',
    'Ecuador',
    'El Salvador',
    'Ethiopia',
    'Guatemala',
    'Honduras',
    'Indonesia',
    'Kenya',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Papua New Guinea',
    'Peru',
    'Rwanda',
    'Sulawesi',
    'Sumatra',
    'Tanzania',
    'Uganda',
    'Various',
  ] as const,

  roasters: [
    'Airship',
    'Alma',
    'Anodyne',
    'Atomic',
    'Bean & Bean',
    'Bird Rock',
    'Blueprint',
    'Boxcar',
    'Broadcast',
    'Broadsheet',
    'Caffe Vita',
    'Cerberus',
    'Common Voice',
    'Cuvée Coffee',
    'DOMA',
    'Drink Coffee Do Stuff',
    'Dune',
    'Equator',
    'Feast',
    'George Howell',
    'Gimme!',
    'Good Citizen',
    'Greater Goods',
    'Highwire',
    'Huckleberry',
    'Irving Farm',
    'Joe',
    'Klatch',
    'Kuma',
    'Maquina',
    'Methodical',
    'Metric',
    'Mother Tongue',
    'Necessary',
    'Novo',
    "Oren's Coffee",
    "PT's",
    'Panther',
    'Passenger',
    'Peixoto',
    'PERC',
    'Portrait',
    'ReAnimator',
    'Red Rooster',
    'Roasted Record',
    'Sightglass',
    'Sightseer',
    'Small Planes',
    'Sparrows',
    'Steady State',
    'Sterling Coffee Roasters',
    'Temple',
    'Verve',
    'Wonderstate',
  ] as const,

  // bagWeights: [
  //   'Small Bag (8 oz.)',
  //   'Standard Bag (10.93 oz)',
  //   'Big Bag (2 lb.)',
  //   'Bulk (5 lb.)',
  // ] as const,

  processes: [
    'Experimental/Other',
    'Honey',
    'Natural/Dry Processed',
    'Pulped Natural',
    'Pulped Natural/Honey',
    'Washed',
    'Wet-hulled',
  ] as const,

  certifications: [
    'Certified Organic',
    'Fair Trade',
    'Kosher',
    'Rainforest Alliance',
  ] as const,

  tasteTypes: [
    'Chocolaty & Sweet',
    'Funky & Fruity',
    'Sweet & Inviting',
    'Sweet & Tart',
    'Subtle & Delicate',
    'Roasty & Smoky',
    'Comforting & Rich',
    'Balanced & Fruity',
    'Sweet & Smooth',
    'Syrupy & Smooth',
  ] as const,
} as const;

// Type definitions for better TypeScript support
export type RoastLevel = typeof COFFEE_OPTIONS.roastLevels[number];
export type TastingNote = typeof COFFEE_OPTIONS.tastingNotes[number];
// export type PriceRange = typeof COFFEE_OPTIONS.priceRanges[number];
export type Region = typeof COFFEE_OPTIONS.regions[number];
export type Origin = typeof COFFEE_OPTIONS.origins[number];
export type Roaster = typeof COFFEE_OPTIONS.roasters[number];
// export type BagWeight = typeof COFFEE_OPTIONS.bagWeights[number];
export type Process = typeof COFFEE_OPTIONS.processes[number];
export type Certification = typeof COFFEE_OPTIONS.certifications[number];
export type TasteType = typeof COFFEE_OPTIONS.tasteTypes[number]; 